# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

power_two_grp_fixed_a0 <- function(dType, n_t, n_c, historical, p_t_prior_samps, p_c_prior_samps, b_t1, b_t2, b_01, b_02, delta, gamma, N, upper_inf) {
    .Call(`_BayesPPD_power_two_grp_fixed_a0`, dType, n_t, n_c, historical, p_t_prior_samps, p_c_prior_samps, b_t1, b_t2, b_01, b_02, delta, gamma, N, upper_inf)
}

two_grp_fixed_a0_normal <- function(y_c, n_c, v, historical, nMC, nBI) {
    .Call(`_BayesPPD_two_grp_fixed_a0_normal`, y_c, n_c, v, historical, nMC, nBI)
}

power_two_grp_fixed_a0_normal <- function(n_t, n_c, historical, mu_t_prior_samps, mu_c_prior_samps, var_t_prior_samps, var_c_prior_samps, delta, gamma, nMC, nBI, N) {
    .Call(`_BayesPPD_power_two_grp_fixed_a0_normal`, n_t, n_c, historical, mu_t_prior_samps, mu_c_prior_samps, var_t_prior_samps, var_c_prior_samps, delta, gamma, nMC, nBI, N)
}

glm_fixed_a0 <- function(dType0, dLink0, y0, n0, x0, historical0, lower_limits0, upper_limits0, slice_widths0, nMC, nBI, dCurrent0) {
    .Call(`_BayesPPD_glm_fixed_a0`, dType0, dLink0, y0, n0, x0, historical0, lower_limits0, upper_limits0, slice_widths0, nMC, nBI, dCurrent0)
}

glm_fixed_a0_normal <- function(y, x, historical, nMC, nBI) {
    .Call(`_BayesPPD_glm_fixed_a0_normal`, y, x, historical, nMC, nBI)
}

power_glm_fixed_a0 <- function(dType0, dLink0, n_total, n0, historical0, x_samps, beta_c_prior_samps, var_prior_samps, lower_limits0, upper_limits0, slice_widths0, delta, gamma, nMC, nBI, N, dCurrent0) {
    .Call(`_BayesPPD_power_glm_fixed_a0`, dType0, dLink0, n_total, n0, historical0, x_samps, beta_c_prior_samps, var_prior_samps, lower_limits0, upper_limits0, slice_widths0, delta, gamma, nMC, nBI, N, dCurrent0)
}

two_grp_random_a0 <- function(dType0, y0, n0, historical0, b_010, b_020, c_10, c_20, lower_limits0, upper_limits0, slice_widths0, nMC, nBI) {
    .Call(`_BayesPPD_two_grp_random_a0`, dType0, y0, n0, historical0, b_010, b_020, c_10, c_20, lower_limits0, upper_limits0, slice_widths0, nMC, nBI)
}

two_grp_random_a0_normal <- function(y0, n0, v0, historical0, c_10, c_20, lower_limits0, upper_limits0, slice_widths0, nMC, nBI) {
    .Call(`_BayesPPD_two_grp_random_a0_normal`, y0, n0, v0, historical0, c_10, c_20, lower_limits0, upper_limits0, slice_widths0, nMC, nBI)
}

glm_random_a0_normal <- function(y_normal0, x_normal0, historical_normal0, c_10, c_20, lower_limits0, upper_limits0, slice_widths0, nMC, nBI) {
    .Call(`_BayesPPD_glm_random_a0_normal`, y_normal0, x_normal0, historical_normal0, c_10, c_20, lower_limits0, upper_limits0, slice_widths0, nMC, nBI)
}

power_two_grp_random_a0 <- function(dType0, n_t, n0, historical0, mu_t_prior_samps, mu_c_prior_samps, var_t_prior_samps, var_c_prior_samps, b_t1, b_t2, b_010, b_020, c_10, c_20, lower_limits0, upper_limits0, slice_widths0, delta, gamma, nMC, nBI, N) {
    .Call(`_BayesPPD_power_two_grp_random_a0`, dType0, n_t, n0, historical0, mu_t_prior_samps, mu_c_prior_samps, var_t_prior_samps, var_c_prior_samps, b_t1, b_t2, b_010, b_020, c_10, c_20, lower_limits0, upper_limits0, slice_widths0, delta, gamma, nMC, nBI, N)
}

power_glm_random_a0_normal <- function(n_total, historical0, beta_c_prior_samps, var_prior_samps, c_10, c_20, lower_limits0, upper_limits0, slice_widths0, delta, gamma, nMC, nBI, N) {
    .Call(`_BayesPPD_power_glm_random_a0_normal`, n_total, historical0, beta_c_prior_samps, var_prior_samps, c_10, c_20, lower_limits0, upper_limits0, slice_widths0, delta, gamma, nMC, nBI, N)
}

glm_random_a0 <- function(dType0, dLink0, y0, n0, x0, historical0, c_10, c_20, coef0, lower_limits0, upper_limits0, slice_widths0, nMC, nBI) {
    .Call(`_BayesPPD_glm_random_a0`, dType0, dLink0, y0, n0, x0, historical0, c_10, c_20, coef0, lower_limits0, upper_limits0, slice_widths0, nMC, nBI)
}

power_glm_random_a0 <- function(dType0, dLink0, n_total, n0, historical0, beta_c_prior_samps, c_10, c_20, coef0, lower_limits0, upper_limits0, slice_widths0, delta, gamma, nMC, nBI, N) {
    .Call(`_BayesPPD_power_glm_random_a0`, dType0, dLink0, n_total, n0, historical0, beta_c_prior_samps, c_10, c_20, coef0, lower_limits0, upper_limits0, slice_widths0, delta, gamma, nMC, nBI, N)
}

